FROM ubuntu:20.04

LABEL mad162pumpkin="dmjon162@yandex.ru"

RUN apt-get update && \
    apt-get install -y default-jre && \
    apt-get install -y default-jdk && \
    apt-get install -y git && \
    apt-get clean

ADD https://github.com/mad162pumpkin/Java_D.git

RUN git clone https://github.com/mad162pumpkin/Java_D.git

WORKDIR /Java_D

RUN java test.java
