# Установка образа ОС
FROM ubuntu:20.04

# Указание автора образа
LABEL mad162pumpkin="dmjon162@yandex.ru"

# Установка необходимых компонентов системы
RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/* &&\
    apt-get clean

# Добавление репозитория контейнера
ADD https://github.com/mad162pumpkin/FQW.git skipcache

# Копирование репозитория с кодом для проверки
RUN git clone https://github.com/mad162pumpkin/JS_D.git

# Переход в директорию с кодом
WORKDIR /JS_D

# Запуск кода для проверки
RUN node test.js
