FROM ubuntu:20.04

LABEL mad162pumpkin="dmjon162@yandex.ru"

RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get install -y git && \
    apt-get clean

ARG NOCACHEBUST=1
CMD
RUN git clone https://github.com/mad162pumpkin/JS_D.git &&\
    apt-get clean

WORKDIR /JS_D
CMD
RUN node test.js
