FROM ubuntu:20.04

LABEL mad162pumpkin="dmjon162@yandex.ru"

RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get install -y git && \
    apt-get clean

ADD https://github.com/mad162pumpkin/FQW.git skipcache

RUN git clone https://github.com/mad162pumpkin/JS_D.git &&\
    apt-get clean

WORKDIR /JS_D

RUN node test.js

RUN rm -rf /JS_D
